#pragma once

#include "chunk_prefill.hpp"

// =============================================================================
// Configuration: Add new policies here
// =============================================================================
// To add a new head size policy, simply add it to this X-Macro list:
// X(policy_name)
#define CHUNK_POLICY_LIST(X) \
  X(chunk_policy_head64)     \
  X(chunk_policy_head96)     \
  X(chunk_policy_head128)    \
  X(chunk_policy_head192)    \
  X(chunk_policy_head256)

// =============================================================================
// Automatic extern template declarations for all policy combinations
// =============================================================================
// Prevent implicit instantiation of policy_dispatch_impl in translation units
// that include chunk_prefill.hpp. Each specialization is explicitly
// instantiated in its own .cpp file generated by CMake.

// Helper macro to declare a single extern template instantiation
#define DECLARE_POLICY_DISPATCH_EXTERN(POLICY, PAGED, CAUSAL, LOCAL, SINK) \
  extern template void                                                     \
  policy_dispatch_impl<POLICY, PAGED, CAUSAL, LOCAL, SINK>(                \
      sycl::queue & queue,                                                 \
      CutlassQKOType & cuQKOType,                                          \
      const chunk_prefill_args_t& args);

// Generate all 16 bool combinations for a given policy using nested macros
// Pattern: Paged, Causal, Local, Sink (all permutations of 4 bools = 2^4 = 16)
// This hierarchical approach makes it easy to extend to more bool parameters

// Level 4: Iterate over Sink values (innermost)
#define DECLARE_FOR_SINK(POLICY, PAGED, CAUSAL, LOCAL)                \
  DECLARE_POLICY_DISPATCH_EXTERN(POLICY, PAGED, CAUSAL, LOCAL, false) \
  DECLARE_POLICY_DISPATCH_EXTERN(POLICY, PAGED, CAUSAL, LOCAL, true)

// Level 3: Iterate over Local values
#define DECLARE_FOR_LOCAL(POLICY, PAGED, CAUSAL) \
  DECLARE_FOR_SINK(POLICY, PAGED, CAUSAL, false) \
  DECLARE_FOR_SINK(POLICY, PAGED, CAUSAL, true)

// Level 2: Iterate over Causal values
#define DECLARE_FOR_CAUSAL(POLICY, PAGED) \
  DECLARE_FOR_LOCAL(POLICY, PAGED, false) \
  DECLARE_FOR_LOCAL(POLICY, PAGED, true)

// Level 1: Iterate over Paged values (outermost)
#define DECLARE_ALL_BOOL_COMBINATIONS(POLICY) \
  DECLARE_FOR_CAUSAL(POLICY, false)           \
  DECLARE_FOR_CAUSAL(POLICY, true)

// Apply the bool combination generator to all policies
CHUNK_POLICY_LIST(DECLARE_ALL_BOOL_COMBINATIONS)

// Cleanup macros
#undef DECLARE_ALL_BOOL_COMBINATIONS
#undef DECLARE_FOR_CAUSAL
#undef DECLARE_FOR_LOCAL
#undef DECLARE_FOR_SINK
#undef DECLARE_POLICY_DISPATCH_EXTERN
